

= JDoc.jl
Daniel Carrera
v0.1 alpha

Documentation system for Julia.


== API

Basic ussage:

----
using JDoc

str = readdoc("example.jl")

doc = jdoc(str)

println( reprmime("text/html", doc) )
----


== Online help

Use to `@doc` macro to add entries to the online help. You can use `@doc`
to document methods, functions, constants, and other Julia objects.

----
@doc "About method foo(x::Int) ..." function foo(x::Int) ... end
@doc "About method foo(x::Real) ..." foo(x::Real) = ...
@doc "About object foo ..." foo
----

=== backend

The documentation is stored in a global dictionary object called `DOC`.
The `help()` function looks up values inside `DOC`. You should not modify
`DOC` directly unless you know what you are doing. The keys are arbitrary
Julia objects and the values are dictionaries. The main documentation
should be in `DOC[obj][:doc]`.


== Writing manuals


=== readdoc

Given an IO stream or file name, this function extracts all the docstrings,
including those in `include`d files.


=== JDoc markup

JDoc is a human-readable markup language. It is a small subset of AsciiDoc,
intended to provide enough features for source code documentation while
keeping the implementation simple.

JDoc can be naturally extended by using additional features from AsciiDoc
and a standard AsciiDoc processor. The two main implementations are
http://asciidoc.org[asciidoc] and http://asciidoctor.org[Asciidoctor].

=== Status

The current parser can read headings, most block types (tables are passed
verbatim), and all paragraph types (NOTE, TIP, WARNING, etc.).

----
= Head 1

== Head 2

=== Head 3

==== Head 4

===== Head 5

This is a paragraph.

TIP: This is a paragraph.

NOTE: This is a paragraph.

WARNING: This is a paragraph.

CAUTION: This is a paragraph.

IMPORTANT: This is a paragraph.

  ....
  Literal line 1
  Literal line 2
  ....
  
  ----
  Listing line 1
  Listing line 2
  ----
  
  ====
  Example line 1
  Example line 2
  ====
  
  ****
  Sidebar line 1
  Sidebar line 2
  ****
  
  ____
  Verse line 1
  Verse line 2
  ____
  
  |===
  Table line 1
  Table line 2
  |===
  
  ++++
  Pass line 1
  Pass line 2
  ++++
  
  ////
  Comment line 1
  Comment line 2
  ////
----
