

== Doc.jl

----
Author:  Daniel Carrera
Version: v0.1.0-alpha
----

A modern documentation system for Julia.

Doc.jl is a documentation module for Julia. It provides features for
both online help and for writing manual-style documentation. Doc.jl is
currently alpha software. If you are feeling adventurous, you are
encouraged to give it a try. This page summarizes the current status of
Doc.jl, and a description of the *DocDoc* markup format. You may complement
this document with the wiki. This document is divided in three parts:


API:: A lightning tour of the Doc.jl API, for those who want to write their
own scripts using DocDoc.

Online help:: How Doc.jl will let you add your function's documentation to
the online help.

Manuals:: How Doc.jl will make it easier for you to write and maintain a
manual for your product.


=== API

Basic usage:

----
using DocDoc

doc"
This is a docstring. Docstrings contain program documentation
that can be extracted and parsed by the DocDoc module.
"

# Extract docstrings from a file.
str = readdoc("example.jl")

# Parse the string as DocDoc markup.
doc = docdoc(str)

# Convert to HTML.
writemime(STDOUT, "text/html", doc)
----

docstring:: A documentation string -- _docstring_ -- is a string literal of
the form `doc" ... "` or `doc""" ... """`. They are used to mark
source documentation that is not part of the online help.

readdoc(_source_):: Given an IO stream or file name, this function extracts
all the docstrings, respecting `include` directives.

docdoc(_docstr_):: Takes a string and parses it as *DocDoc* markup. The resulting
object can be converted to various formats such as HTML and LaTeX.

writemime(_stream, mime, doc_):: Doc.jl uses the  `writemime` framework
to convert documentation objects into other formats. Currently supported
MIME types include:

|===
|`text/plain` | Raw docstring without any processing.
|`text/xml`   | Convert to XML (Docbook).
|`text/html`  | Convert to HTML.
|`text/dump`  | Produce a dump tree useful for debugging.
|===


=== Online help

Use to `@doc` macro to add entries to the online help. You can use `@doc`
to document methods, functions, constants, and other Julia objects.

----
@doc "About method foo(x::Int) ..." function foo(x::Int) ... end
@doc "About method foo(x::Real) ..." foo(x::Real) = ...
@doc "About object foo ..." foo
----

==== backend

The documentation is stored in a global dictionary object called `DOC`.
The `man()` function looks up values inside `DOC`. You should not modify
`DOC` directly unless you know what you are doing. The keys are arbitrary
Julia objects and the values are dictionaries. The main documentation
should be in `DOC[obj][:doc]`.


=== Writing manuals

==== Command-line program: `docdoc`

This module includes a short script called `docdoc`, which uses the API described
above to extract and process documentation in Julia files. The program can print
the original raw string, or convert it to supported formats:

----
docdoc example.jl          # Output raw docstring.
docdoc --plain example.jl  # Output raw docstring.
docdoc --dump  exampe.jl   # Output a dump tree.
docdoc --html  exampe.jl   # Output HTML.
docdoc --xml   exampe.jl   # Output XML (Docbook).
----


==== DocDoc markup

*DocDoc* is a human-readable markup language. It is a small subset of AsciiDoc,
intended to provide enough features for source code documentation while
keeping the implementation simple. *DocDoc* can be naturally extended by using
additional features from AsciiDoc and a standard AsciiDoc processor. The
two main implementations are http://asciidoc.org[asciidoc] and
http://asciidoctor.org[Asciidoctor]. The current parser supports the
following features:

Headings::
----
= Head 1

== Head 2

=== Head 3

==== Head 4

===== Head 5
----


Paragraphs:: Including admonition paragraphs (TIP, NOTE, WARNING, CAUTION
IMPORTANT.):
----
This is a paragraph.

TIP: This is a paragraph.

NOTE: This is a paragraph.

WARNING: This is a paragraph.

CAUTION: This is a paragraph.

IMPORTANT: This is a paragraph.
----

Blocks:: Most block types supported. Tables are passed verbatim.
----
  ....
  Literal line 1
  Literal line 2
  ....
  
  ----
  Listing line 1
  Listing line 2
  ----
  
  ====
  Example line 1
  Example line 2
  ====
  
  ****
  Sidebar line 1
  Sidebar line 2
  ****
  
  ____
  Verse line 1
  Verse line 2
  ____
  
  |===
  Table line 1
  Table line 2
  |===
  
  ++++
  Pass line 1
  Pass line 2
  ++++
  
  ////
  Comment line 1
  Comment line 2
  ////
----
