

== JDoc.jl

----
Author:  Daniel Carrera
Version: v0.1 alpha
----

A modern documentation system for Julia.

JDoc.jl is a documentation module for Julia. It provides features for
both online help and for writing manual-style documentation. JDoc is
currently alpha software. If you are feeling adventurous, you are
ecouraged to give it a try. This page summarizes the current status of
JDoc.jl, and a description of the JDoc markup format. You may complement
this document with the wiki. This document is divided in three parts:


API:: A lightining tour of the JDoc API, for those who want to write their
own scripts using JDoc.

Online help:: How JDoc will let you add your function's documentation to
the `help()` command.

Manuals:: How JDoc will make it easier for you to write and maintain a
manual for your product.


=== API

Basic ussage:

----
using JDoc

doc"
This is a docstring. Docstrings contain program documentation
that can be extracted and parsed by the JDoc module.
"

# Extract docstrings from a file.
str = readdoc("example.jl")

# Parse the string as JDoc markup.
doc = jdoc(str)

# Convert to HTML.
writemime(STDOUT, "text/html", doc)
----

readdoc(source):: Given an IO stream or file name, this function extracts
all the docstrings, respecting `include` directives.

jdoc(docstr):: Takes a string and parses it as JDoc markup. The resulting
object can be converted to various formats such as HTML.


=== Online help

Use to `@doc` macro to add entries to the online help. You can use `@doc`
to document methods, functions, constants, and other Julia objects.

----
@doc "About method foo(x::Int) ..." function foo(x::Int) ... end
@doc "About method foo(x::Real) ..." foo(x::Real) = ...
@doc "About object foo ..." foo
----

==== backend

The documentation is stored in a global dictionary object called `DOC`.
The `help()` function looks up values inside `DOC`. You should not modify
`DOC` directly unless you know what you are doing. The keys are arbitrary
Julia objects and the values are dictionaries. The main documentation
should be in `DOC[obj][:doc]`.


=== Writing manuals


==== JDoc markup

JDoc is a human-readable markup language. It is a small subset of AsciiDoc,
intended to provide enough features for source code documentation while
keeping the implementation simple.

JDoc can be naturally extended by using additional features from AsciiDoc
and a standard AsciiDoc processor. The two main implementations are
http://asciidoc.org[asciidoc] and http://asciidoctor.org[Asciidoctor].

The current parser can read headings, most block types (tables are passed
verbatim), and all paragraph types (NOTE, TIP, WARNING, etc.).

----
= Head 1

== Head 2

=== Head 3

==== Head 4

===== Head 5

This is a paragraph.

TIP: This is a paragraph.

NOTE: This is a paragraph.

WARNING: This is a paragraph.

CAUTION: This is a paragraph.

IMPORTANT: This is a paragraph.

  ....
  Literal line 1
  Literal line 2
  ....
  
  ----
  Listing line 1
  Listing line 2
  ----
  
  ====
  Example line 1
  Example line 2
  ====
  
  ****
  Sidebar line 1
  Sidebar line 2
  ****
  
  ____
  Verse line 1
  Verse line 2
  ____
  
  |===
  Table line 1
  Table line 2
  |===
  
  ++++
  Pass line 1
  Pass line 2
  ++++
  
  ////
  Comment line 1
  Comment line 2
  ////
----
